doc: 增加sig-cloud_provider
DragonOS-Community/Community pull request #15
Opened 2024-06-04 09:00 UTC by 1037827920

2024-06-04 10:28 UTC, Samuka007 requested changes
缺少添加 .vuepress/config.js sigs下条目，具体可参考 #9

2024-06-04 10:48 UTC, Samuka007 requested changes
改一下，PMC不归这里😂

2024-06-04 10:48 UTC, Samuka007 commented on sigs/sig-cloud_provider/README.md
> +- PMC联络人：[@ZZJJWarth](https://github.com/ZZJJWarth) [@1037827920](https://github.com/1037827920)
不是 你俩也不都是PMC啊
你们都在Project Manage Committee吗 😂

2024-06-04 10:49 UTC, Samuka007 approved these changes
ok

2024-06-04 10:51 UTC, 1037827920 commented on sigs/sig-cloud_provider/README.md
> +- PMC联络人：[@ZZJJWarth](https://github.com/ZZJJWarth) [@1037827920](https://github.com/1037827920)
不知道PMC是啥😢😢，那这里就不写咯？

2024-06-04 10:52 UTC, Samuka007 requested changes
修改上述问题

2024-06-04 10:52 UTC, Samuka007 commented on sigs/sig-cloud_provider/README.md
> +- PMC联络人：[@ZZJJWarth](https://github.com/ZZJJWarth) [@1037827920](https://github.com/1037827920)
```suggestion
```
直接删掉就好

2024-06-04 10:56 UTC, Samuka007 approved these changes
r? @fslongjin

2024-06-08 15:29 UTC, fslongjin commented on sigs/sig-cloud_provider/README.md
> +- PMC联络人：[@ZZJJWarth](https://github.com/ZZJJWarth) [@1037827920](https://github.com/1037827920)
PMC联络人指的是，PMC要找人的时候，找谁。因此这个是不用删掉的

2024-06-08 15:39 UTC, 1037827920 commented on sigs/sig-cloud_provider/README.md
> +- PMC联络人：[@ZZJJWarth](https://github.com/ZZJJWarth) [@1037827920](https://github.com/1037827920)
ok

2024-06-09 08:33 UTC, fslongjin requested changes

2024-06-09 08:33 UTC, fslongjin commented on sigs/sig-cloud_provider/README.md
> +**VirtIO-blk支持**
子项目不是这么具体的内容，而是比较宽泛的。比如你们现在正在做移植到腾讯云/阿里云，那这就是1个子项目。

2024-06-09 09:21 UTC, 1037827920 commented on sigs/sig-cloud_provider/README.md
> +**VirtIO-blk支持**
ok

2024-07-03 14:45 UTC, fslongjin approved these changes

2024-07-03 14:45 UTC, merged