完善SIG-Network条目
DragonOS-Community/Community pull request #9
Opened 2024-05-26 12:24 UTC by Samuka007

完善SIG-Network部分相关信息

2024-05-27 16:09 UTC, fslongjin commented on .vuepress/config.js
> +                                text: 'SIG模版',
这里好像不能这样子嵌套的，我上次试了会导致文件夹内的其他文件没法正常显示

2024-05-27 16:10 UTC, fslongjin commented on sigs/sig-network/README.md
> +解决 epoll 管理 socket 所遇到的具体问题。
这种属于具体的issue或者问题，不属于子项目的范畴。因为子项目他要有比较明确的代码范围。

2024-05-27 16:12 UTC, fslongjin commented on sigs/sig-network/README.md
> +- #### Loopback层
包括这种代码里面的具体实现，也不应该出现在sig的描述文档里面。这个是用来描述社区内容的，而不是描述具体的技术细节的。具体的可以去参考k8s的community仓库的sig文档

2024-05-27 16:12 UTC, fslongjin requested changes
上面的问题需要更改

2024-06-04 08:32 UTC, Samuka007 commented on .vuepress/config.js
> +                                text: 'SIG模版',
更新了框架

2024-06-04 08:33 UTC, Samuka007 commented on sigs/sig-network/README.md
> +- #### Loopback层
现在先直接列出子项目，然后给出维护人与Contact（项目链接）了。

2024-06-04 08:42 UTC, Samuka007 commented on sigs/sig-network/README.md
> +### 解决actix-web与epoll的适配
还需要改个标题。

2024-06-04 09:38 UTC, Samuka007 commented on sigs/sig-network/README.md
> +解决 epoll 管理 socket 所遇到的具体问题。
已修改范畴

2024-06-09 08:32 UTC, fslongjin requested changes

2024-06-09 08:32 UTC, fslongjin commented on sigs/sig-network/README.md
> +~~以下是SIG-template参与并支持的 [工作组]~~
这里需要更改

2024-06-09 08:32 UTC, fslongjin commented on sigs/sig-network/README.md
> +### Loopback网卡实现
子项目感觉可以分为以下2个，

- 网卡驱动
- Epoll

2024-07-03 14:57 UTC, merged